apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
  - namespace: default
    name: in-cluster
  - namespace: argocd
    name: in-cluster
  - namespace: monitoring
    name: in-cluster
  sourceRepos:
  - '*'
  sourceNamespaces:
  - monitoring
  roles:
  - name: read-write
    policies:
    - p, applications, applications-sync, default/*

