apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: web
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
  - namespace: argocd
  - namespace: api
  - namespace: client
  sourceRepos:
  - '*'
  sourceNamespaces:
  - api
  - client
  roles:
  - name: read-write
    policies:
    - p, applications, applications-sync, default/*
