apiVersion: v1
kind: Service
metadata:
  name: basicwebapp-service
  namespace: client
  labels:
    app: client
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: client