apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webpage
  namespace: argocd
spec:
  project: default
  source:
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  syncPolicy:
    automated: {}
