apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: basic-web-app
          image: basic-web-image:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000