apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: monitoring
spec:
  project: web
  source:
    repoURL: https://github.com/JulienFuix/MiniKube_ArgoCD_Manifest
    targetRevision: HEAD
    path: monitoring
  destination:
    namespace: monitoring
    name: in-cluster