apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: api
spec:
  project: web
  source:
    repoURL: https://github.com/JulienFuix/MiniKube_ArgoCD_Manifest
    targetRevision: HEAD
    path: /web/api
  destination:
    name: in-cluster
    namespace: api