apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicapi
  namespace: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: basicapi
          image: basicapi:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3001