apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JulienFuix/MiniKube_ArgoCD_Manifest
    targetRevision: HEAD
    path: chartmuseum
  destination:
    namespace: default
    name: in-cluster