apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmuseum
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chartmuseum
  template:
    metadata:
      labels:
        app: chartmuseum
    spec:
      containers:
        - name: chartmuseum
          image: chartmuseum/chartmuseum:v0.12.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3004
          env:
            - name: DEBUG
              value: "true"
            - name: STORAGE
              value: "local"
            - name: STORAGE_LOCAL_ROOTDIR
              value: "/tmp/charts"