apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmuseum
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chartmuseum
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: chartmuseum
          image: ghcr.io/helm/chartmuseum:v0.14.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3004