apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: default
spec:
  project: web
  source:
    chart: web
    repoURL: http://localhost:8084
    targetRevision: 0.1.0
    helm:
      releaseName: web
  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    syncOptions:
    - CreateNamespace=true