apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: default
spec:
  project: web
  source:
    repoURL: https://github.com/JulienFuix/MiniKube_ArgoCD_Manifest
    targetRevision: HEAD
    path: web
  destination:
    namespace: default
    name: in-cluster