apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: default
  annotations:
    argocd.argoproj.io/application.parent: argocd
spec:
  project: web
  source:
    repoURL: https://github.com/JulienFuix/MiniKube_ArgoCD_Manifest
    targetRevision: HEAD
    path: /web
  destination:
    server: https://kubernetes.default.svc
    namespace: default